### ISSUE TITLE
Change of baits options

### ISSUE THREAD

**Issue by noaskers** [EvenMoreFish/EvenMoreFish#301]
This is a bait but right now it only returns that its boosts one kind of fish rarity is it possible to make it that I can show what rarity its boosts

Or lets say make a custom lore for every bait 

![image](https://github.com/Oheers/EvenMoreFish/assets/90572779/3e2f8c57-8090-4017-a966-9f8ba8dada14)

**Comment by noaskers** [comment]
If this is not possible it would be nice to make this a suggestion ^

**Comment by noaskers** [comment]
```
    rarities:
      - "Epische"
      - "Tropische"
    lore:
      - "&7Verhoogt epische en legendarische vissen."
    catch-weight: 2
    application-weight: 5
    max-baits: 1
    ```
    
    Looking at this it should be possible
