### ISSUE TITLE
Rework ItemFactory and its configs

### ISSUE THREAD

**Issue by FireML** [EvenMoreFish/EvenMoreFish#611]
### Suggestion

I would like to rework the ItemFactory class to clean up its code and make it easier to read.

ItemFactory configs should be slightly reworked to make things more clear:

Old Config (Using the default nbt-rod):
```yaml
nbt-rod-item:
  item:
    material: FISHING_ROD
    displayname: <yellow>EvenMoreFish Fishing Rod
  glowing: true
  lore:
  - ''
  - <gray>Catch </gray><yellow>custom </yellow><gray>fish using this
  - <gray>fishing rod.
```

New Config:
```yaml
nbt-rod-item:
  item:
    material: FISHING_ROD
    displayname: <yellow>EvenMoreFish Fishing Rod
    glowing: true
    lore:
    - ''
    - <gray>Catch </gray><yellow>custom </yellow><gray>fish using this
    - <gray>fishing rod.
```
Everything is under the item key instead of some inside and some outside, this will make it more clear.
