### ISSUE TITLE
[Suggestion (Plugin)]: Allow `allowed-rarities` to apply to every competition type

### ISSUE THREAD

**Issue by FireML** [EvenMoreFish/EvenMoreFish#617]
### Suggestion

Have `allowed-rarities` in competitions work for every type instead of the "specific" types.

This will require a lot of work, so it may take a while to do.

**Comment by FireML** [comment]
Added ActiveCompetitionRequirementType as an alternative to this.

```yaml
requirements:
  # Passes if the active competition matches any in the list.
  active-competition:
    - mainCompetition
    - testCompetition
```
